eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8001
spring:
  application:
    name: order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.100.1.100:3307/seata-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Root@123#

logging:
  level:
    io:
      seata: debug